const AppRoutes = {
  Home: "/",
  Login: "/login",
  Register: "/register",
  Forgot: "/forgot/:token",
  Verification: "/verification",
  ChangePassword: "/change/:token",
  Logout: "/logout",
  NotFound: "/404",
  Contact: "/contact",
  Checkout: "/checkout",
  Profile: "/profile",
  ClientArea: "/area",
  ProfileBilling: "/profile/billing",
  Orders: "/orders",
  ToS: "/tos",
  AdminDashboard: "/admin",
  AdminOrders: "/admin/orders",
  AdminOrderAdd: "/admin/orders/add",
  AdminOrderEdit: "/admin/orders/edit/:id",
  AdminProducts: "/admin/products",
  AdminProductAdd: "/admin/products/add",
  AdminProductEdit: "/admin/products/edit/:id",
  AdminProductCategories: "/admin/products/categories",
  AdminProductCategoryAdd: "/admin/products/categories/add",
  AdminProductCategoryEdit: "/admin/products/categories/edit/:id",
  AdminProductRegions: "/admin/products/regions",
  AdminProductRegionAdd: "/admin/products/regions/add",
  AdminProductRegionEdit: "/admin/products/regions/edit/:id",
  AdminUsers: "/admin/users",
  AdminUserPermissions: "/admin/users/permissions",
  AdminUserPermissionAdd: "/admin/users/permissions/add",
  AdminUserPermissionEdit: "/admin/users/permissions/edit/:id"
};

export default AppRoutes;
