const AppRoutes = {
  Home: "/",
  Login: "/login",
  Register: "/register",
  Forgot: "/forgot/:token",
  Verification: "/verification",
  ChangePassword: "/change/:token",
  Logout: "/logout",
  NotFound: "/404",
  Contact: "/contact",
  CheckoutComplete: "/checkout/complete/:type",
  ClientArea: "/area",
  Profile: "/profile",
  ProfileBilling: "/profile/billing",
  Orders: "/orders",
  ToS: "/tos",
  AdminDashboard: "/admin",
  AdminOrders: "/admin/orders",
  AdminProducts: "/admin/products",
  AdminServers: "/admin/servers",
  AdminUsers: "/admin/users",
  AdminUserPermissions: "/admin/users/permissions",
};

export default AppRoutes;
